### ISSUE TITLE
Are you a drama subtitle writer?

### ISSUE THREAD

**Issue by RblSb** [kudoamine/adblock#1]
Sorry, I couldn't find other contacts besides your nickname.

I would like to know if you have srt subtitles for `Zero: Ikkaku Senkin Game Special EP Mitsuru Part 1` and for `Part 2`. These episodes are hardsubbed, but i would like to translate original subs files to show this show to a friend. Sorry if you are another person.

**Comment by kudoamine** [comment]
Hi, yeah I am the guy who own that blog.

Unfortunately I don't have the subs for those episodes, I just took the videos from another source and the subs were already hardcoded.
Here is the original source: https://news4p.livejournal.com/4756.html

Your best bet is contacting them if they have somehow kept the subs.

**Comment by kudoamine** [comment]
The group might've been private to join, I don't remember, I contacted them myself, I'll let you know if they ever respond.

**Comment by RblSb** [comment]
Thanks for the information, but I already tried one free OCR service (subtitleextractor.com) and it did a great job of converting hardsubs into srt for further translation.

Thank you very much for your work, although all the links on the blog are dead, I was able to download all the subtitles from Google Player and convert them to srt. Without this blog, I would have missed such a nice fukumoto adaptation.

**Comment by kudoamine** [comment]
Indeed, this drama was great, any fukumoto content is appreciated.

The download links are dead indeed, I should just enable the download for the google drive videos, I just didn't get the time to do it, I should soon.

Good luck in your translation.
